/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppViagemAtivaRouteImport } from './routes/app.viagem-ativa'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMinhasCaronasRouteImport } from './routes/app.minhas-caronas'
import { Route as AppCriarRotaRouteImport } from './routes/app.criar-rota'
import { Route as AppCarteiraRouteImport } from './routes/app.carteira'
import { Route as AppBuscarRouteImport } from './routes/app.buscar'
import { Route as AppPerfilIndexRouteImport } from './routes/app.perfil.index'
import { Route as AppRotaIdRouteImport } from './routes/app.rota.$id'
import { Route as AppPerfilVisualizarRouteImport } from './routes/app.perfil.visualizar'
import { Route as AppPerfilPrivacidadeRouteImport } from './routes/app.perfil.privacidade'
import { Route as AppPerfilConfiguracoesRouteImport } from './routes/app.perfil.configuracoes'
import { Route as AppPerfilConexoesRouteImport } from './routes/app.perfil.conexoes'
import { Route as AppChatRotaIdRouteImport } from './routes/app.chat.$rotaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppViagemAtivaRoute = AppViagemAtivaRouteImport.update({
  id: '/viagem-ativa',
  path: '/viagem-ativa',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhasCaronasRoute = AppMinhasCaronasRouteImport.update({
  id: '/minhas-caronas',
  path: '/minhas-caronas',
  getParentRoute: () => AppRoute,
} as any)
const AppCriarRotaRoute = AppCriarRotaRouteImport.update({
  id: '/criar-rota',
  path: '/criar-rota',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteiraRoute = AppCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppRotaIdRoute = AppRotaIdRouteImport.update({
  id: '/rota/$id',
  path: '/rota/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilVisualizarRoute = AppPerfilVisualizarRouteImport.update({
  id: '/visualizar',
  path: '/visualizar',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppPerfilPrivacidadeRoute = AppPerfilPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppPerfilConfiguracoesRoute = AppPerfilConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppPerfilConexoesRoute = AppPerfilConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppChatRotaIdRoute = AppChatRotaIdRouteImport.update({
  id: '/chat/$rotaId',
  path: '/chat/$rotaId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/criar-rota': typeof AppCriarRotaRoute
  '/app/minhas-caronas': typeof AppMinhasCaronasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/viagem-ativa': typeof AppViagemAtivaRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$rotaId': typeof AppChatRotaIdRoute
  '/app/perfil/conexoes': typeof AppPerfilConexoesRoute
  '/app/perfil/configuracoes': typeof AppPerfilConfiguracoesRoute
  '/app/perfil/privacidade': typeof AppPerfilPrivacidadeRoute
  '/app/perfil/visualizar': typeof AppPerfilVisualizarRoute
  '/app/rota/$id': typeof AppRotaIdRoute
  '/app/perfil/': typeof AppPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/criar-rota': typeof AppCriarRotaRoute
  '/app/minhas-caronas': typeof AppMinhasCaronasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/viagem-ativa': typeof AppViagemAtivaRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$rotaId': typeof AppChatRotaIdRoute
  '/app/perfil/conexoes': typeof AppPerfilConexoesRoute
  '/app/perfil/configuracoes': typeof AppPerfilConfiguracoesRoute
  '/app/perfil/privacidade': typeof AppPerfilPrivacidadeRoute
  '/app/perfil/visualizar': typeof AppPerfilVisualizarRoute
  '/app/rota/$id': typeof AppRotaIdRoute
  '/app/perfil': typeof AppPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/criar-rota': typeof AppCriarRotaRoute
  '/app/minhas-caronas': typeof AppMinhasCaronasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/viagem-ativa': typeof AppViagemAtivaRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$rotaId': typeof AppChatRotaIdRoute
  '/app/perfil/conexoes': typeof AppPerfilConexoesRoute
  '/app/perfil/configuracoes': typeof AppPerfilConfiguracoesRoute
  '/app/perfil/privacidade': typeof AppPerfilPrivacidadeRoute
  '/app/perfil/visualizar': typeof AppPerfilVisualizarRoute
  '/app/rota/$id': typeof AppRotaIdRoute
  '/app/perfil/': typeof AppPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/buscar'
    | '/app/carteira'
    | '/app/criar-rota'
    | '/app/minhas-caronas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/viagem-ativa'
    | '/app/'
    | '/app/chat/$rotaId'
    | '/app/perfil/conexoes'
    | '/app/perfil/configuracoes'
    | '/app/perfil/privacidade'
    | '/app/perfil/visualizar'
    | '/app/rota/$id'
    | '/app/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/buscar'
    | '/app/carteira'
    | '/app/criar-rota'
    | '/app/minhas-caronas'
    | '/app/notificacoes'
    | '/app/viagem-ativa'
    | '/app'
    | '/app/chat/$rotaId'
    | '/app/perfil/conexoes'
    | '/app/perfil/configuracoes'
    | '/app/perfil/privacidade'
    | '/app/perfil/visualizar'
    | '/app/rota/$id'
    | '/app/perfil'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/buscar'
    | '/app/carteira'
    | '/app/criar-rota'
    | '/app/minhas-caronas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/viagem-ativa'
    | '/app/'
    | '/app/chat/$rotaId'
    | '/app/perfil/conexoes'
    | '/app/perfil/configuracoes'
    | '/app/perfil/privacidade'
    | '/app/perfil/visualizar'
    | '/app/rota/$id'
    | '/app/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/viagem-ativa': {
      id: '/app/viagem-ativa'
      path: '/viagem-ativa'
      fullPath: '/app/viagem-ativa'
      preLoaderRoute: typeof AppViagemAtivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minhas-caronas': {
      id: '/app/minhas-caronas'
      path: '/minhas-caronas'
      fullPath: '/app/minhas-caronas'
      preLoaderRoute: typeof AppMinhasCaronasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/criar-rota': {
      id: '/app/criar-rota'
      path: '/criar-rota'
      fullPath: '/app/criar-rota'
      preLoaderRoute: typeof AppCriarRotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carteira': {
      id: '/app/carteira'
      path: '/carteira'
      fullPath: '/app/carteira'
      preLoaderRoute: typeof AppCarteiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buscar': {
      id: '/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil/': {
      id: '/app/perfil/'
      path: '/'
      fullPath: '/app/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/rota/$id': {
      id: '/app/rota/$id'
      path: '/rota/$id'
      fullPath: '/app/rota/$id'
      preLoaderRoute: typeof AppRotaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil/visualizar': {
      id: '/app/perfil/visualizar'
      path: '/visualizar'
      fullPath: '/app/perfil/visualizar'
      preLoaderRoute: typeof AppPerfilVisualizarRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/perfil/privacidade': {
      id: '/app/perfil/privacidade'
      path: '/privacidade'
      fullPath: '/app/perfil/privacidade'
      preLoaderRoute: typeof AppPerfilPrivacidadeRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/perfil/configuracoes': {
      id: '/app/perfil/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/perfil/configuracoes'
      preLoaderRoute: typeof AppPerfilConfiguracoesRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/perfil/conexoes': {
      id: '/app/perfil/conexoes'
      path: '/conexoes'
      fullPath: '/app/perfil/conexoes'
      preLoaderRoute: typeof AppPerfilConexoesRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/chat/$rotaId': {
      id: '/app/chat/$rotaId'
      path: '/chat/$rotaId'
      fullPath: '/app/chat/$rotaId'
      preLoaderRoute: typeof AppChatRotaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPerfilRouteChildren {
  AppPerfilConexoesRoute: typeof AppPerfilConexoesRoute
  AppPerfilConfiguracoesRoute: typeof AppPerfilConfiguracoesRoute
  AppPerfilPrivacidadeRoute: typeof AppPerfilPrivacidadeRoute
  AppPerfilVisualizarRoute: typeof AppPerfilVisualizarRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
}

const AppPerfilRouteChildren: AppPerfilRouteChildren = {
  AppPerfilConexoesRoute: AppPerfilConexoesRoute,
  AppPerfilConfiguracoesRoute: AppPerfilConfiguracoesRoute,
  AppPerfilPrivacidadeRoute: AppPerfilPrivacidadeRoute,
  AppPerfilVisualizarRoute: AppPerfilVisualizarRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
}

const AppPerfilRouteWithChildren = AppPerfilRoute._addFileChildren(
  AppPerfilRouteChildren,
)

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppCarteiraRoute: typeof AppCarteiraRoute
  AppCriarRotaRoute: typeof AppCriarRotaRoute
  AppMinhasCaronasRoute: typeof AppMinhasCaronasRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRouteWithChildren
  AppViagemAtivaRoute: typeof AppViagemAtivaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatRotaIdRoute: typeof AppChatRotaIdRoute
  AppRotaIdRoute: typeof AppRotaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppCarteiraRoute: AppCarteiraRoute,
  AppCriarRotaRoute: AppCriarRotaRoute,
  AppMinhasCaronasRoute: AppMinhasCaronasRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRouteWithChildren,
  AppViagemAtivaRoute: AppViagemAtivaRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatRotaIdRoute: AppChatRotaIdRoute,
  AppRotaIdRoute: AppRotaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
